### ISSUE TITLE
Should update non-NRCan author emails

### ISSUE THREAD

**Issue by thompsdk** [nrcan-cfs-fire/cffdrs#7]
Schicks and Flannigan contact info could be updated too with their Ontario and TRU emails, respectively

**Comment by BadgerOnABike** [comment]
Do you have those emails handy, I'll drop em in now.

**Comment by alancan** [comment]
Thomas.Schiks@ontario.ca
mflannigan@tru.ca

**Comment by thompsdk** [comment]
***@***.***>

***@***.***
